## Numpy - 2

In [1]:
import numpy as np

In [7]:
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [8]:
np.arange(1,37).reshape(6,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

In [9]:
np.arange(1,37).reshape(6,7)

ValueError: cannot reshape array of size 36 into shape (6,7)

#slicing in matrix

In [13]:
a = np.random.randint(10,25,(5,5))
a

array([[20, 21, 16, 12, 21],
       [16, 16, 18, 17, 12],
       [10, 19, 23, 12, 23],
       [21, 19, 24, 12, 16],
       [13, 11, 15, 13, 18]], dtype=int32)

In [14]:
type(a)

numpy.ndarray

In [15]:
a[:] # print entire matrix

array([[20, 21, 16, 12, 21],
       [16, 16, 18, 17, 12],
       [10, 19, 23, 12, 23],
       [21, 19, 24, 12, 16],
       [13, 11, 15, 13, 18]], dtype=int32)

In [16]:
a[1:3] #print the two rows(1 , 2 rows)

array([[16, 16, 18, 17, 12],
       [10, 19, 23, 12, 23]], dtype=int32)

In [19]:
a[1,2] # print the specific value in matrix

np.int32(18)

In [20]:
a[1.2]   # it is do not print because the "." dot

np.int32(18)

In [21]:
a[1,-1]

np.int32(12)

In [23]:
a[2:3]

array([[10, 19, 23, 12, 23]], dtype=int32)

In [24]:
a[0,3]

np.int32(12)

In [25]:
a[-5,-3]

np.int32(16)

In [26]:
a[-6,99]

IndexError: index -6 is out of bounds for axis 0 with size 5

# numpy oparations

In [31]:
b = np.random.randint(10,20,12)
b

array([13, 17, 11, 14, 14, 19, 10, 15, 16, 15, 13, 12], dtype=int32)

In [32]:
id(b)

2172308024624

In [36]:
arr1 = np.random.randint(0,100,(10,10))
arr1

array([[66, 10, 51, 26, 70, 21, 89, 93, 75, 72],
       [12, 43, 67,  6, 56, 46, 52, 41, 38, 35],
       [45, 84, 57, 41, 24,  7, 98,  6,  1, 45],
       [63, 30, 28, 30, 99, 23, 14, 72, 95, 60],
       [99, 34, 28, 45, 91, 88, 71, 85, 72,  7],
       [70, 99, 18, 70, 89, 81, 26, 48, 71,  8],
       [78,  4,  0, 83, 38, 18, 17, 59, 67, 58],
       [82, 39, 81, 86, 84, 50, 76, 22, 66, 19],
       [33,  5, 55, 51, 50, 93, 26, 86, 82, 65],
       [ 8, 42, 84, 82, 64, 47, 71, 51, 79, 40]], dtype=int32)

In [38]:
arr1[2:6]

array([[45, 84, 57, 41, 24,  7, 98,  6,  1, 45],
       [63, 30, 28, 30, 99, 23, 14, 72, 95, 60],
       [99, 34, 28, 45, 91, 88, 71, 85, 72,  7],
       [70, 99, 18, 70, 89, 81, 26, 48, 71,  8]], dtype=int32)

In [40]:
arr1[:3]

array([[66, 10, 51, 26, 70, 21, 89, 93, 75, 72],
       [12, 43, 67,  6, 56, 46, 52, 41, 38, 35],
       [45, 84, 57, 41, 24,  7, 98,  6,  1, 45]], dtype=int32)

In [43]:
arr1[2:-5]

array([[45, 84, 57, 41, 24,  7, 98,  6,  1, 45],
       [63, 30, 28, 30, 99, 23, 14, 72, 95, 60],
       [99, 34, 28, 45, 91, 88, 71, 85, 72,  7]], dtype=int32)

In [45]:
arr1[-2:-5]

array([], shape=(0, 10), dtype=int32)

In [47]:
arr1[:]

array([[66, 10, 51, 26, 70, 21, 89, 93, 75, 72],
       [12, 43, 67,  6, 56, 46, 52, 41, 38, 35],
       [45, 84, 57, 41, 24,  7, 98,  6,  1, 45],
       [63, 30, 28, 30, 99, 23, 14, 72, 95, 60],
       [99, 34, 28, 45, 91, 88, 71, 85, 72,  7],
       [70, 99, 18, 70, 89, 81, 26, 48, 71,  8],
       [78,  4,  0, 83, 38, 18, 17, 59, 67, 58],
       [82, 39, 81, 86, 84, 50, 76, 22, 66, 19],
       [33,  5, 55, 51, 50, 93, 26, 86, 82, 65],
       [ 8, 42, 84, 82, 64, 47, 71, 51, 79, 40]], dtype=int32)

In [48]:
arr1[::-1]

array([[ 8, 42, 84, 82, 64, 47, 71, 51, 79, 40],
       [33,  5, 55, 51, 50, 93, 26, 86, 82, 65],
       [82, 39, 81, 86, 84, 50, 76, 22, 66, 19],
       [78,  4,  0, 83, 38, 18, 17, 59, 67, 58],
       [70, 99, 18, 70, 89, 81, 26, 48, 71,  8],
       [99, 34, 28, 45, 91, 88, 71, 85, 72,  7],
       [63, 30, 28, 30, 99, 23, 14, 72, 95, 60],
       [45, 84, 57, 41, 24,  7, 98,  6,  1, 45],
       [12, 43, 67,  6, 56, 46, 52, 41, 38, 35],
       [66, 10, 51, 26, 70, 21, 89, 93, 75, 72]], dtype=int32)

In [49]:
arr1[::-5]

array([[ 8, 42, 84, 82, 64, 47, 71, 51, 79, 40],
       [99, 34, 28, 45, 91, 88, 71, 85, 72,  7]], dtype=int32)

In [50]:
arr1[:-1]

array([[66, 10, 51, 26, 70, 21, 89, 93, 75, 72],
       [12, 43, 67,  6, 56, 46, 52, 41, 38, 35],
       [45, 84, 57, 41, 24,  7, 98,  6,  1, 45],
       [63, 30, 28, 30, 99, 23, 14, 72, 95, 60],
       [99, 34, 28, 45, 91, 88, 71, 85, 72,  7],
       [70, 99, 18, 70, 89, 81, 26, 48, 71,  8],
       [78,  4,  0, 83, 38, 18, 17, 59, 67, 58],
       [82, 39, 81, 86, 84, 50, 76, 22, 66, 19],
       [33,  5, 55, 51, 50, 93, 26, 86, 82, 65]], dtype=int32)

In [51]:
arr1[:3]

array([[66, 10, 51, 26, 70, 21, 89, 93, 75, 72],
       [12, 43, 67,  6, 56, 46, 52, 41, 38, 35],
       [45, 84, 57, 41, 24,  7, 98,  6,  1, 45]], dtype=int32)

In [53]:
arr1.max()

np.int32(99)

In [54]:
arr1.min()

np.int32(0)

In [58]:
arr1.mean()

np.float64(52.32)

In [60]:
arr1.median()  # this functions is not working

AttributeError: 'numpy.ndarray' object has no attribute 'median'

# Matrix

In [61]:
mat = np.arange(0,100).reshape(10,10)
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [66]:
r = 2
c = 2

In [67]:
mat[r,c]

np.int64(22)

In [68]:
mat[4]

array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [69]:
mat[4][4]

np.int64(44)

In [72]:
mat[:4] # with slices

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [73]:
mat[4:]

array([[40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [74]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [79]:
mat[0:10,0:1]  # print the first coloum 

array([[ 0],
       [10],
       [20],
       [30],
       [40],
       [50],
       [60],
       [70],
       [80],
       [90]])

In [81]:
mat[0:10,4:6] # print the 4 , 5 coloums

array([[ 4,  5],
       [14, 15],
       [24, 25],
       [34, 35],
       [44, 45],
       [54, 55],
       [64, 65],
       [74, 75],
       [84, 85],
       [94, 95]])

# Masking in numpy(filter)

In [83]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [84]:
mat < 25

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [85]:
mat[mat < 25]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [88]:
mat[mat > 25]

array([26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42,
       43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59,
       60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76,
       77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93,
       94, 95, 96, 97, 98, 99])

In [91]:
mat[mat == 50]

array([50])

In [92]:
mat[mat != 50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [95]:
i = np.eye(4 , dtype = int) # creat an identi matrix
i

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])