# STARTED NUMPY

In [2]:
import numpy as np  # installing NUMPY 

In [3]:
np.__version__ #.__version__ for know any version

'1.26.4'

In [4]:
import sys
sys.version

'3.12.7 | packaged by Anaconda, Inc. | (main, Oct  4 2024, 13:17:27) [MSC v.1929 64 bit (AMD64)]'

# creating list

In [6]:
my_list = [0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [7]:
type(my_list)

list

In [8]:
arr = np.array(my_list)

In [9]:
arr

array([0, 1, 2, 3, 4, 5])

In [10]:
type(arr)

numpy.ndarray

In [11]:
type(my_list)

list

# arange function 

In [ ]:
np. # we press tab for seeing functionalities

In [33]:
np.arange(10) # this is one d array #int data type

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
np.arange(20) 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [30]:
np.arange(50)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [31]:
np.arange (10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
np.arange(5.0) # float data type

array([0., 1., 2., 3., 4.])

In [34]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

np.arange(10,20) # it act like a range function

In [44]:
np.arange(20, 10) #element should be lessthan then the second one 

array([], dtype=int32)

In [45]:
np.arange (-20, 10) # -20 is lessthan the 10

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [46]:
np.arange(10, 30, 5) # range and step count was 5

array([10, 15, 20, 25])

In [47]:
 np.arange(10, 30, 5, 2) # its not coz there is nopossible terms - in range function we acant add 4 numbers


TypeError: Cannot interpret '2' as a data type

# zeros function

In [51]:
np.zeros(10,) # parameter tunning

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [54]:
np.zeros(10, dtype = int) # we change this flot into int - known as hyper tunning


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [57]:
np.zeros((2,2), dtype = int) #2d array

array([[0, 0],
       [0, 0]])

In [58]:
np.zeros((2,10), dtype = int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [59]:
np.zeros((10,10), dtype = int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

# ones function

In [60]:
np.ones(3)

array([1., 1., 1.])

In [61]:
np.ones(3, dtype=int)

array([1, 1, 1])

In [69]:
a = np.ones((3,3),dtype= int)

In [70]:
a

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [73]:
np.twos((2,3))

AttributeError: module 'numpy' has no attribute 'twos'

# rand function

In [74]:
rand(3,2)

NameError: name 'rand' is not defined

In [75]:
random.rand(2,3)

NameError: name 'random' is not defined

In [79]:
np.random.rand(2,3) #NP is a package 
                    #RANDOM is a module
                    #RAND is a function

array([[0.96765392, 0.13107861, 0.46696888],
       [0.89214594, 0.872383  , 0.11910307]])

In [81]:
np.random.rand(5)

array([0.76730846, 0.77836236, 0.19597226, 0.81624846, 0.84026157])

In [82]:
np.random.randint(5)

1

In [83]:
np.random.rand(5,10)

array([[0.0532688 , 0.17646501, 0.18042996, 0.49111825, 0.91187564,
        0.36671185, 0.50728941, 0.51964552, 0.07281675, 0.69091292],
       [0.85242785, 0.48887266, 0.15709725, 0.46178667, 0.8200993 ,
        0.78410444, 0.20592055, 0.15732331, 0.15061347, 0.15272831],
       [0.89670179, 0.34424371, 0.1765993 , 0.3212582 , 0.50513012,
        0.30705086, 0.5219478 , 0.4113044 , 0.15873939, 0.73581277],
       [0.58783039, 0.97422808, 0.72898649, 0.44736577, 0.61580609,
        0.85707957, 0.28087609, 0.44203683, 0.49213728, 0.75990679],
       [0.98245805, 0.58135401, 0.91834646, 0.56119285, 0.49838505,
        0.84703373, 0.77358247, 0.35588983, 0.51452783, 0.29686042]])

In [84]:
np.random.randint(5,10)

6

In [86]:
np.random.randint(2, 20 , 4)

array([18,  4, 17,  7])

In [89]:
np.random.randint(0,1)

0